package az.kapitalbank.msemployee.error;

public interface ErrorCode {
    String INVALID_TOKEN = "INVALID_TOKEN";
    String INVALID_LOGIN_DETAILS = "INVALID_LOGIN_DETAILS";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND";
    String DUPLICATE_RECORD = "DUPLICATE_RECORD";
    String METHOD_NOT_SUPPORTED = "METHOD NOT SUPPORTED";
    String VALIDATION_ERROR = "VALIDATION_ERROR";
}
